"""
QuickAPI CLI Tool

Command-line interface for QuickAPI development and deployment.
"""

import os
import sys
import argparse
import subprocess
from pathlib import Path
from typing import Optional

from .utils import get_logger

logger = get_logger(__name__)


def create_project(name: str, directory: Optional[str] = None):
    """Create a new QuickAPI project"""
    if directory is None:
        directory = name
    
    # Create project directory
    project_path = Path(directory)
    project_path.mkdir(exist_ok=True)
    
    # Create basic project structure
    (project_path / "app.py").write_text(f'''"""
QuickAPI Application

A simple QuickAPI application example.
"""

from quickapi import QuickAPI
from quickapi.middleware import CORSMiddleware

app = QuickAPI(title="{name} API", version="1.0.0")

# Add CORS middleware
app.middleware(CORSMiddleware(allow_origins=["*"]))

@app.get("/")
async def root():
    return {{"message": "Welcome to {name} API!"}}

@app.get("/health")
async def health():
    return {{"status": "healthy"}}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
''')
    
    # Create requirements.txt
    (project_path / "requirements.txt").write_text('''quickapi
uvicorn[standard]
''')
    
    # Create README
    (project_path / "README.md").write_text(f'''# {name}

A QuickAPI application.

## Installation

```bash
pip install -r requirements.txt
```

## Running

```bash
python app.py
```

## API Documentation

Visit http://localhost:8000/docs for interactive API documentation.
''')
    
    print(f"✅ Created QuickAPI project '{name}' in '{directory}'")
    print(f"📁 To get started:")
    print(f"   cd {directory}")
    print(f"   pip install -r requirements.txt")
    print(f"   python app.py")


def run_server(app_file: str = "app.py", host: str = "0.0.0.0", port: int = 8000, reload: bool = False):
    """Run the development server"""
    if not os.path.exists(app_file):
        print(f"❌ Error: App file '{app_file}' not found")
        sys.exit(1)
    
    print(f"🚀 Starting QuickAPI server on http://{host}:{port}")
    print(f"📚 API docs available at http://{host}:{port}/docs")
    
    # Run with uvicorn
    cmd = [
        "uvicorn",
        f"{app_file.replace('.py', '')}:app",
        "--host", host,
        "--port", str(port)
    ]
    
    if reload:
        cmd.append("--reload")
    
    subprocess.run(cmd)


def create_dockerfile():
    """Create a Dockerfile for the project"""
    dockerfile_content = '''FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
'''
    
    Path("Dockerfile").write_text(dockerfile_content)
    print("✅ Created Dockerfile")


def create_docker_compose():
    """Create a docker-compose.yml file"""
    compose_content = '''version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - .:/app
'''
    
    Path("docker-compose.yml").write_text(compose_content)
    print("✅ Created docker-compose.yml")


def install_dependencies():
    """Install QuickAPI and its dependencies"""
    print("📦 Installing QuickAPI...")
    
    try:
        subprocess.run([sys.executable, "-m", "pip", "install", "quickapi"], check=True)
        print("✅ QuickAPI installed successfully")
    except subprocess.CalledProcessError:
        print("❌ Failed to install QuickAPI")
        sys.exit(1)


def generate_openapi(app_file: str = "app.py", output: str = "openapi.json"):
    """Generate OpenAPI specification"""
    try:
        # Import the app module
        import importlib.util
        spec = importlib.util.spec_from_file_location("app", app_file)
        app_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(app_module)
        
        # Get the app instance
        app = getattr(app_module, "app", None)
        if not app:
            print(f"❌ Error: No 'app' variable found in {app_file}")
            sys.exit(1)
        
        # Generate OpenAPI spec
        openapi_spec = {
            "openapi": "3.0.0",
            "info": {
                "title": app.title,
                "version": app.version,
                "description": f"Generated by QuickAPI"
            },
            "paths": app.router.generate_openapi_paths()
        }
        
        # Write to file
        import json
        with open(output, "w") as f:
            json.dump(openapi_spec, f, indent=2)
        
        print(f"✅ OpenAPI specification generated: {output}")
        
    except Exception as e:
        print(f"❌ Error generating OpenAPI spec: {e}")
        sys.exit(1)


def main():
    """Main CLI entry point"""
    parser = argparse.ArgumentParser(description="QuickAPI CLI Tool")
    subparsers = parser.add_subparsers(dest="command", help="Available commands")
    
    # Create command
    create_parser = subparsers.add_parser("create", help="Create a new QuickAPI project")
    create_parser.add_argument("name", help="Project name")
    create_parser.add_argument("--dir", help="Project directory (default: project name)")
    
    # Run command
    run_parser = subparsers.add_parser("run", help="Run the development server")
    run_parser.add_argument("--app", default="app.py", help="App file (default: app.py)")
    run_parser.add_argument("--host", default="0.0.0.0", help="Host (default: 0.0.0.0)")
    run_parser.add_argument("--port", type=int, default=8000, help="Port (default: 8000)")
    run_parser.add_argument("--reload", action="store_true", help="Enable auto-reload")
    
    # Docker commands
    docker_parser = subparsers.add_parser("docker", help="Docker-related commands")
    docker_subparsers = docker_parser.add_subparsers(dest="docker_command")
    
    dockerfile_parser = docker_subparsers.add_parser("file", help="Create Dockerfile")
    compose_parser = docker_subparsers.add_parser("compose", help="Create docker-compose.yml")
    
    # Install command
    install_parser = subparsers.add_parser("install", help="Install QuickAPI")
    
    # OpenAPI command
    openapi_parser = subparsers.add_parser("openapi", help="Generate OpenAPI specification")
    openapi_parser.add_argument("--app", default="app.py", help="App file (default: app.py)")
    openapi_parser.add_argument("--output", default="openapi.json", help="Output file (default: openapi.json)")
    
    # Parse arguments
    args = parser.parse_args()
    
    # Execute command
    if args.command == "create":
        create_project(args.name, args.dir)
    elif args.command == "run":
        run_server(args.app, args.host, args.port, args.reload)
    elif args.command == "docker":
        if args.docker_command == "file":
            create_dockerfile()
        elif args.docker_command == "compose":
            create_docker_compose()
        else:
            docker_parser.print_help()
    elif args.command == "install":
        install_dependencies()
    elif args.command == "openapi":
        generate_openapi(args.app, args.output)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()